export const AdvisoryAgencies = [
  {
    name: 'Văn phòng Tỉnh ủy',
    alias: 'https://vanphong.vinhlong.dcs.vn',
  },
  {
    name: 'Ban Tổ chức Tỉnh ủy',
    alias: 'https://bantochuc.vinhlong.dcs.vn',
  },
  {
    name: 'Ban Nội chính Tỉnh ủy',
    alias: 'https://bannoichinh.vinhlong.dcs.vn',
  },
  {
    name: 'Ủy ban Kiểm Tra Tỉnh ủy',
    alias: 'https://uybankiemtra.vinhlong.dcs.vn',
  },
  {
    name: 'Ban Tuyên giáo và Dân vận Tỉnh ủy',
    alias: 'https://tuyengiaodanvan.vinhlong.dcs.vn',
  },
];

export const ProvincialAgencies = [
  {
    name: 'Đảng ủy các cơ quan Đảng tỉnh',
    alias: 'https://duccoquandang.vinhlong.dcs.vn/',
  },
];
export const WardOrCommune = [
  {
    WardOrCommuneCol: [
      { name: 'Phường Long Đức', alias: 'phuong-long-duc' },
      { name: 'Phường Trà Vinh', alias: 'phuong-tra-vinh' },
      { name: 'Phường Nguyệt Hóa', alias: 'phuong-nguyet-hoa' },
      { name: 'Phường Hòa Thuận', alias: 'phuong-hoa-thuan' },
      { name: 'Phường Duyên Hải', alias: 'phuong-duyen-hai' },
      { name: 'Phường Trường Long Hòa', alias: 'phuong-truong-long-hoa' },
      { name: 'Xã An Trường', alias: 'xa-an-truong' },
      { name: 'Xã Tân An', alias: 'xa-tan-an' },
      { name: 'Xã Càng Long', alias: 'xa-cang-long' },
      { name: 'Xã Nhị Long', alias: 'xa-nhi-long' },
      { name: 'Xã Bình Phú', alias: 'xa-binh-phu' },
      { name: 'Xã Song Lộc', alias: 'xa-song-loc' },
      { name: 'Xã Châu Thành', alias: 'xa-chau-thanh' },
      { name: 'Xã Hưng Mỹ', alias: 'xa-hung-my' },
      { name: 'Xã Hòa Minh', alias: 'xa-hoa-minh' },
      { name: 'Xã Long Hòa', alias: 'xa-long-hoa' },
      { name: 'Xã Cầu Kè', alias: 'xa-cau-ke' },
      { name: 'Xã Phong Thạnh', alias: 'xa-phong-thanh' },
      { name: 'Xã An Phú Tân', alias: 'xa-an-phu-tan' },
      { name: 'Xã Tam Ngãi', alias: 'xa-tam-ngai' },
      { name: 'Xã Tân Hòa', alias: 'xa-tan-hoa' },
      { name: 'Xã Hùng Hòa', alias: 'xa-hung-hoa' },
      { name: 'Xã Tiểu Cần', alias: 'xa-tieu-can' },
      { name: 'Xã Tập Ngãi', alias: 'xa-tap-ngai' },
      { name: 'Xã Mỹ Long', alias: 'xa-my-long' },
      { name: 'Xã Vinh Kim', alias: 'xa-vinh-kim' },
      { name: 'Xã Cầu Ngang', alias: 'xa-cau-ngang' },
      { name: 'Xã Nhị Trường', alias: 'xa-nhi-truong' },
      { name: 'Xã Hiệp Mỹ', alias: 'xa-hiep-my' },
      { name: 'Xã Lưu Nghiệp Anh', alias: 'xa-luu-nghiep-anh' },
      { name: 'Xã Đại An', alias: 'xa-dai-an' },
      { name: 'Xã Hàm Giang', alias: 'xa-ham-giang' },
      { name: 'Xã Trà Cú', alias: 'xa-tra-cu' },
      { name: 'Xã Long Hiệp', alias: 'xa-long-hiep' },
      { name: 'Xã Tập Sơn', alias: 'xa-tap-son' },
      { name: 'Xã Long Hữu', alias: 'xa-long-huu' },
      { name: 'Xã Long Thành', alias: 'xa-long-thanh' },
      { name: 'Xã Đông Hải', alias: 'xa-dong-hai' },
      { name: 'Xã Long Vĩnh', alias: 'xa-long-vinh' },
      { name: 'Xã Đôn Châu', alias: 'xa-don-chau' },
      { name: 'Xã Ngũ Lạc', alias: 'xa-ngu-lac' },
    ],
  },
  {
    WardOrCommuneCol: [
      { name: 'Phường An Hội', alias: 'phuong-an-hoi' },
      { name: 'Phường Bến Tre', alias: 'phuong-ben-tre' },
      { name: 'Phường Sơn Đông', alias: 'phuong-son-dong' },
      { name: 'Phường Phú Tân', alias: 'phuong-phu-tan' },
      { name: 'Phường Phú Khương', alias: 'phuong-phu-khuong' },
      { name: 'Xã Phú Túc', alias: 'xa-phu-tuc' },
      { name: 'Xã Giao Long', alias: 'xa-giao-long' },
      { name: 'Xã Tiên Thủy', alias: 'xa-tien-thuy' },
      { name: 'Xã Tân Phú', alias: 'xa-tan-phu' },
      { name: 'Xã Hưng Nhượng', alias: 'xa-hung-nhuong' },
      { name: 'Xã Giồng Trôm', alias: 'xa-giong-trom' },
      { name: 'Xã Tân Hào', alias: 'xa-tan-hao' },
      { name: 'Xã Phước Long', alias: 'xa-phuoc-long' },
      { name: 'Xã Lương Phú', alias: 'xa-luong-phu' },
      { name: 'Xã Châu Hòa', alias: 'xa-chau-hoa' },
      { name: 'Xã Lương Hòa', alias: 'xa-luong-hoa' },
      { name: 'Xã Tân Thủy', alias: 'xa-tan-thuy' },
      { name: 'Xã Bảo Thạnh', alias: 'xa-bao-thanh' },
      { name: 'Xã Ba Tri', alias: 'xa-ba-tri' },
      { name: 'Xã Tân Xuân', alias: 'xa-tan-xuan' },
      { name: 'Xã Mỹ Chánh Hòa', alias: 'xa-my-chanh-hoa' },
      { name: 'Xã An Ngãi Trung', alias: 'xa-an-ngai-trung' },
      { name: 'Xã An Hiệp', alias: 'xa-an-hiep' },
      { name: 'Xã Thới Thuận', alias: 'xa-thoi-thuan' },
      { name: 'Xã Thạnh Phước', alias: 'xa-thanh-phuoc' },
      { name: 'Xã Bình Đại', alias: 'xa-binh-dai' },
      { name: 'Xã Thạnh Trị', alias: 'xa-thanh-tri' },
      { name: 'Xã Lộc Thuận', alias: 'xa-loc-thuan' },
      { name: 'Xã Châu Hưng', alias: 'xa-chau-hung' },
      { name: 'Xã Phú Thuận', alias: 'xa-phu-thuan' },
      { name: 'Xã Phú Phụng', alias: 'xa-phu-phung' },
      { name: 'Xã Chợ Lách', alias: 'xa-cho-lach' },
      { name: 'Xã Vĩnh Thành', alias: 'xa-vinh-thanh' },
      { name: 'Xã Hưng Khánh Trung', alias: 'xa-hung-khanh-trung' },
      { name: 'Xã Phước Mỹ Trung', alias: 'xa-phuoc-my-trung' },
      { name: 'Xã Tân Thành Bình', alias: 'xa-tan-thanh-binh' },
      { name: 'Xã Nhuận Phú Tân', alias: 'xa-nhuan-phu-tan' },
      { name: 'Xã Đồng Khởi', alias: 'xa-dong-khoi' },
      { name: 'Xã Mỏ Cày', alias: 'xa-mo-cay' },
      { name: 'Xã Thành Thới', alias: 'xa-thanh-thoi' },
      { name: 'Xã An Định', alias: 'xa-an-dinh' },
      { name: 'Xã Hương Mỹ', alias: 'xa-huong-my' },
      { name: 'Xã Đại Điền', alias: 'xa-dai-dien' },
      { name: 'Xã Quới Điền', alias: 'xa-quoi-dien' },
      { name: 'Xã Thạnh Phú', alias: 'xa-thanh-phu' },
      { name: 'Xã An Qui', alias: 'xa-an-qui' },
      { name: 'Xã Thạnh Hải', alias: 'xa-thanh-hai' },
      { name: 'Xã Thạnh Phong', alias: 'xa-thanh-phong' },
    ],
  },
  {
    WardOrCommuneCol: [
      { name: 'Phường Thanh Đức', alias: 'phuong-thanh-duc' },
      { name: 'Phường Long Châu', alias: 'phuong-long-chau' },
      { name: 'Phường Phước Hậu', alias: 'phuong-phuoc-hau' },
      { name: 'Phường Tân Hạnh', alias: 'phuong-tan-hanh' },
      { name: 'Phường Tân Ngãi', alias: 'phuong-tan-ngai' },
      { name: 'Phường Bình Minh', alias: 'phuong-binh-minh' },
      { name: 'Phường Cái Vồn', alias: 'phuong-cai-von' },
      { name: 'Phường Đông Thành', alias: 'phuong-dong-thanh' },
      { name: 'Xã Cái Nhum', alias: 'xa-cai-nhum' },
      { name: 'Xã Tân Long Hội', alias: 'xa-tan-long-hoi' },
      { name: 'Xã Trà Côn', alias: 'xa-tra-con' },
      { name: 'Xã Nhơn Phú', alias: 'xa-nhon-phu' },
      { name: 'Xã Bình Phước', alias: 'xa-binh-phuoc' },
      { name: 'Xã An Bình', alias: 'xa-an-binh' },
      { name: 'Xã Long Hồ', alias: 'xa-long-ho' },
      { name: 'Xã Phú Quới', alias: 'xa-phu-quoi' },
      { name: 'Xã Quới Thiện', alias: 'xa-quoi-thien' },
      { name: 'Xã Trung Thành', alias: 'xa-trung-thanh' },
      { name: 'Xã Trung Ngãi', alias: 'xa-trung-ngai' },
      { name: 'Xã Quới An', alias: 'xa-quoi-an' },
      { name: 'Xã Trung Hiệp', alias: 'xa-trung-hiep' },
      { name: 'Xã Hiếu Phụng', alias: 'xa-hieu-phung' },
      { name: 'Xã Hiếu Thành', alias: 'xa-hieu-thanh' },
      { name: 'Xã Lục Sỹ Thành', alias: 'xa-luc-sy-thanh' },
      { name: 'Xã Trà Ôn', alias: 'xa-tra-on' },
      { name: 'Xã Vĩnh Xuân', alias: 'xa-vinh-xuan' },
      { name: 'Xã Hòa Bình', alias: 'xa-hoa-binh' },
      { name: 'Xã Hòa Hiệp', alias: 'xa-hoa-hiep' },
      { name: 'Xã Tam Bình', alias: 'xa-tam-binh' },
      { name: 'Xã Ngãi Tứ', alias: 'xa-ngai-tu' },
      { name: 'Xã Song Phú', alias: 'xa-song-phu' },
      { name: 'Xã Cái Ngang', alias: 'xa-cai-ngang' },
      { name: 'Xã Tân Quới', alias: 'xa-tan-quoi' },
      { name: 'Xã Tân Lược', alias: 'xa-tan-luoc' },
      { name: 'Xã Mỹ Thuận', alias: 'xa-my-thuan' },
    ],
  },
];
