export const DataSelect = [
  { alias: 'http://hochiminh.vn', name: 'Trang thông tin điện tử Hồ Chí Minh' },
  { alias: 'https://es.nhandan.vn/', name: 'Nhan dan en línea' },
  { alias: 'http://chinhphu.vn/', name: 'Chính phủ nước CHXHCN VN' },
  { alias: 'http://quochoi.vn/', name: 'Quốc hội nước CHXHCN VN' },
  { alias: 'http://doanthanhnien.vn/', name: 'Trung ương Đoàn TNCS HCM' },
  { alias: 'http://dukcqtw.dcs.vn/', name: 'Đảng ủy Khối các cơ quan TW' },
  {
    alias: 'http://doanhnghieptrunguong.vn/',
    name: 'Đảng ủy Khối doanh nghiệp TW',
  },
  { alias: 'http://ubkttw.vn/', name: 'Ủy ban Kiểm tra Trung ương' },
  { alias: 'http://noichinh.vn/', name: 'Ban Nội chính Trung ương' },
  { alias: 'http://danvan.vn/', name: 'Ban Dân Vận Trung ương' },
  {
    alias: 'https://kinhtetrunguong.vn/',
    name: 'Ban Chính sách, Chiến lược Trung ương',
  },
  { alias: 'http://www.mofa.gov.vn/', name: 'Bộ Ngoại giao' },
  { alias: 'http://nhandan.com.vn/', name: 'Báo Nhân dân' },
  { alias: 'http://www.tapchicongsan.org.vn/', name: 'Tạp chí Cộng sản' },
  { alias: 'http://www.xaydungdang.org.vn/', name: 'Tạp chí Xây dựng Đảng' },
  { alias: 'http://tuyengiao.vn', name: 'Tạp chí Tuyên giáo' },
  { alias: 'http://vnanet.vn/', name: 'Thông tấn xã Việt Nam' },
  { alias: 'http://www.qdnd.vn/', name: 'Quân đội Nhân dân' },
  { alias: 'http://hanoimoi.com.vn/', name: 'Báo Hà Nội mới' },
  { alias: 'http://www.sggp.org.vn/', name: 'Báo Sài Gòn Giải Phóng' },
  { alias: 'http://laodong.com.vn/', name: 'Báo Lao động' },
  { alias: 'http://www.vir.com.vn/', name: 'Báo đầu tư' },
  { alias: 'http://www.gdtd.com.vn/', name: 'Giáo dục thời đại' },
  { alias: 'http://nld.com.vn/', name: 'Người lao động' },
  { alias: 'http://quehuongonline.vn/', name: 'Quê hương' },
  { alias: 'http://vneconomy.vn/', name: 'Thời báo Kinh tế' },
  { alias: 'http://vnexpress.net/', name: 'Tin nhanh' },
  { alias: 'http://vdc.com.vn/', name: 'VDC' },
  { alias: 'http://vietnamnet.vn/', name: 'Vietnamnet' },
  { alias: 'http://www.thudo.gov.vn', name: 'Thủ đô Hà Nội' },
  { alias: 'http://haiphong.gov.vn/', name: 'TP Hải Phòng' },
  {
    alias:
      'http://www.haiphong.gov.vn:8888/Portal/Default.aspx?Organization=TU',
    name: 'Thành ủy Hải Phòng',
  },
  { alias: 'https://dangbodanang.vn/', name: 'Đảng bộ thành phố Đà Nẵng' },
  { alias: 'http://www.vnn.vn/province/danang/index.html', name: 'TP Đà Nẵng' },
  {
    alias: 'https://www.hcmcpv.org.vn/',
    name: 'Đảng bộ thành phố Hồ Chí Minh',
  },
  { alias: 'http://www.hochiminhcity.gov.vn/', name: 'TP Hồ Chí Minh' },
  { alias: 'http://thanhuycantho.vn/', name: 'Đảng bộ thành phố Cần Thơ' },
  { alias: 'http://cantho.gov.vn/', name: 'Cần Thơ' },
  { alias: 'http://www.angiang.dcs.vn/', name: 'Đảng bộ tỉnh An Giang' },
  { alias: 'http://bariavungtau.com/', name: 'Bà Rịa - Vũng Tàu' },
  { alias: 'http://www.bacgiang.gov.vn/', name: 'Bắc Giang' },
  { alias: 'http://bacninh.dcs.vn/', name: 'Đảng bộ tỉnh Bắc Ninh' },
  { alias: 'http://www.izabacninh.gov.vn/', name: 'Bắc Ninh' },
  { alias: 'http://www.bentre.dcs.vn/', name: 'Đảng bộ tỉnh Bến Tre' },
  { alias: 'https://binhdinh.dcs.vn/', name: 'Đảng bộ tỉnh Bình Định' },
  { alias: 'http://www.baobinhdinh.com.vn/', name: 'Báo Bình Định' },
  { alias: 'http://binhduong.gov.vn/', name: 'Bình Dương' },
  { alias: 'https://tinhuybinhphuoc.vn/', name: 'Đảng bộ tỉnh Bình Phước' },
  { alias: 'http://www.binhphuoc.gov.vn/', name: 'Bình Phước' },
  { alias: 'http://www.binhthuan.dcs.vn/', name: 'Đảng bộ tỉnh Bình Thuận' },
  { alias: 'http://www.binhthuan.gov.vn/', name: 'Bình Thuận' },
  { alias: 'http://camau.dcs.vn/', name: 'Đảng bộ tỉnh Cà Mau' },
  { alias: 'http://www.camau.gov.vn/', name: 'Cà Mau' },
  { alias: 'http://www.caobang.gov.vn/', name: 'Cao Bằng' },
  { alias: 'https://daknong.gov.vn/', name: 'Đảng bộ tỉnh Đăk Nông' },
  { alias: 'http://dienbien.dcs.vn/', name: 'Đảng bộ tỉnh Điện Biên' },
  { alias: 'http://www.dongnai.gov.vn/', name: 'Đồng Nai' },
  { alias: 'https://dongthap.gov.vn', name: 'Đồng Tháp' },
  { alias: 'http://tinhuygialai.org.vn/', name: 'Đảng bộ tỉnh Gia Lai' },
  { alias: 'http://hagiang.gov.vn/', name: 'Hà Giang' },
  { alias: 'http://tuhn.vn/', name: 'Đảng bộ tỉnh Hà Nam' },
  { alias: 'http://hanam.gov.vn/', name: 'Hà Nam' },
  { alias: 'https://hatinh.dcs.vn/', name: 'Đảng bộ tỉnh Hà Tĩnh' },
  { alias: 'http://tinhuyhaiduong.vn/', name: 'Đảng bộ tỉnh Hải Dương' },
  { alias: 'http://tinhuyhaugiang.org.vn/', name: 'Tỉnh ủy Hậu Giang' },
  { alias: 'http://tinhuyhoabinh.vn/', name: 'Đảng bộ tỉnh Hòa Bình' },
  { alias: 'http://www.hoabinh.gov.vn/', name: 'Hòa Bình' },
  { alias: 'http://tinhuykhanhhoa.vn/', name: 'Tỉnh ủy Khánh Hòa' },
  { alias: 'http://www.baokhanhhoa.com.vn/', name: 'Báo Khánh Hòa' },
  { alias: 'http://laichau.dcs.vn/', name: 'Tỉnh ủy Lai Châu' },
  { alias: 'https://www.lamdong.dcs.vn/', name: 'Tỉnh ủy Lâm Đồng' },
  { alias: 'http://laocai.org.vn/', name: 'Văn phòng Tỉnh ủy Lào Cai' },
  { alias: 'http://laocai.org/', name: 'Lào Cai' },
  { alias: 'http://longan.dcs.vn/', name: 'Đảng bộ tỉnh Long An' },
  { alias: 'http://namdinh.org.vn/', name: 'Đảng bộ tỉnh Nam Định' },
  { alias: 'https://nghean.dcs.vn/', name: 'Đảng bộ tỉnh Nghệ An' },
  { alias: 'http://nghean.gov.vn/', name: 'Nghệ An' },
  { alias: 'http://tinhuyninhbinh.vn/', name: 'Đảng bộ tỉnh Ninh Bình' },
  { alias: 'http://www.phuyen.gov.vn/', name: 'Phú Yên' },
  { alias: 'http://quangnam.dcs.vn/', name: 'Đảng bộ tỉnh Quảng Nam' },
  { alias: 'http://www.quangnam.gov.vn/', name: 'Quảng Nam' },
  { alias: 'https://www.quangngai.dcs.vn/', name: 'Đảng bộ tỉnh Quảng Ngãi' },
  { alias: 'http://www.quangngai.gov.vn/', name: 'Quảng Ngãi' },
  { alias: 'http://halong.vnn.vn/', name: 'TP Hạ Long' },
  { alias: 'https://tinhuyquangtri.vn/', name: 'Đảng bộ tỉnh Quảng Trị' },
  { alias: 'https://soctrang.dcs.vn/', name: 'Đảng bộ tỉnh Sóc Trăng' },
  { alias: 'http://www.baosonla.org.vn/', name: 'Báo Sơn La' },
  { alias: 'http://www.tayninh.dcs.vn/', name: 'Đảng bộ tỉnh Tây Ninh' },
  { alias: 'http://www.cinet.vnn.vn/tay-ninh/index.htm', name: 'Tây Ninh' },
  { alias: 'http://www.thainguyen.gov.vn/', name: 'Thái Nguyên' },
  { alias: 'https://thanhhoa.dcs.vn/', name: 'Tỉnh ủy Thanh Hóa' },
  { alias: 'http://thanhhoa.gov.vn/', name: 'Thanh Hóa' },
  { alias: 'https://tinhuytthue.vn/', name: 'Tỉnh ủy Thừa Thiên Huế' },
  { alias: 'http://netcodo.com.vn/', name: 'TP Huế' },
  { alias: 'https://travinh.dcs.vn/', name: 'Đảng bộ tỉnh Trà Vinh' },
  { alias: 'https://tuyenquang.dcs.vn/', name: 'Đảng bộ tỉnh Tuyên Quang' },
  { alias: 'https://vinhlong.dcs.vn/', name: 'Tỉnh ủy Vĩnh Long' },
  { alias: 'http://kprf.ru/', name: 'ĐCS Liên bang Nga' },
  { alias: 'http://www.cpusa.org/', name: 'ĐCS Mỹ' },
  { alias: 'http://www.pcf.fr/', name: 'ĐCS Pháp' },
  { alias: 'http://www.chinatoday.com/', name: 'ĐCS Trung Quốc' },
  { alias: 'http://www.people.com.cn/', name: 'Mạng Nhân dân Trung Hoa' },
];
